services:
  fkbd-ghost:
    image: ghost:latest
    container_name: fkbd-ghost
    restart: unless-stopped
    depends_on:
      - fkbd-ghostdb
    networks:
      - proxy
    environment:
      url: https://fkbd.xyz
      database__client: mysql
      database__connection__host: fkbd-ghostdb
      database__connection__user: root
      database__connection__password: $GHOSTDB_ROOT_PASSWORD
      database__connection__database: ghost
    volumes:
      - /opt/fkbd-ghost/content:/var/lib/ghost/content
      - /opt/fkbd-ghost/config.production.json:/var/lib/ghost/config.production.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fkbd.entrypoints=http"
      - "traefik.http.routers.fkbd.rule=Host(`fkbd.xyz`)"
      - "traefik.http.middlewares.fkbd-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.fkbd.middlewares=fkbd-https-redirect"
      - "traefik.http.routers.fkbd-secure.entrypoints=https"
      - "traefik.http.routers.fkbd-secure.rule=Host(`fkbd.xyz`)"
      - "traefik.http.routers.fkbd-secure.tls=true"
      - "traefik.http.routers.fkbd-secure.service=fkbd"
      - "traefik.http.services.fkbd.loadbalancer.server.port=2368"
      - "traefik.docker.network=proxy"

  fkbd-ghostdb:
    image: mysql:latest
    container_name: fkbd-ghostdb
    ports:
      - 3306:3306
    networks:
      - proxy
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $GHOSTDB_ROOT_PASSWORD
    volumes:
      - /opt/fkbd-ghost/mysql:/var/lib/mysql

volumes:
  mysql:
  content:
  config:

networks:
  proxy:
    external: true
